### ISSUE TITLE
Runtime-generated regexps?

### ISSUE THREAD

**Issue by adnelson** [myfreeweb/pcre-heavy#10]
All of the examples given in the readme use regexes that are known at compile time. What if I need to use information which isn't known until runtime? For example, if I want to have a function which takes a string as an argument, and builds a regex which searches for that string?

**Comment by adnelson** [comment]
A related topic is composing regexes. For example, if I have a regex which parses emails:

``` haskell
emailRegex :: Regex
```

is it possible to use that regex inside of another regex, without copy/pasting the regex syntax?

**Comment by valpackett** [comment]
@adnelson The Regex type is just the Regex from pcre-light. If you look at the source for the quasiquoter, it just calls PCRE.compile. So you can use that.

(Also, consider using something other than regexes. Like (atto)parsec. It's very composable.)

**Comment by adnelson** [comment]
OK, great to know! Yeah parsec is great, sometimes you just want something quick and dirty though :) isn't that why you wrote this library? :sweat_smile:
